// Generated by `wit-bindgen` 0.41.0. DO NOT EDIT!
#ifndef __BINDINGS_CALCULATOR_WORLD_H
#define __BINDINGS_CALCULATOR_WORLD_H
#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include <stdbool.h>
#include <stddef.h>

// Exported Functions from `example:math/calculator`
int32_t exports_example_math_calculator_add(int32_t a, int32_t b);

#ifdef __cplusplus
}
#endif
#endif
